import type { Entry, Manifest } from "./manifest.js"

export const CATALOGUE_START = "<!-- option catalogue: generated by `pnpm parity:render` from parity.json -->"
export const CATALOGUE_END = "<!-- end of the option catalogue -->"

const cell = (text: string) => text.replaceAll("|", "\\|").replaceAll("\n", " ")

const where = (entry: Entry) => {
  if (entry === "all" || entry.in === "all") return ""
  if (Object.keys(entry.planned ?? {}).length > 0) return " (planned)"
  return entry.in.length === 1 ? ` (${entry.in[0]}-only)` : ` (${entry.in.join(", ")} only)`
}

/** The option catalogue as a Markdown table: each option once, and the commands that take it. */
export const renderCatalogue = (manifest: Manifest): string => {
  const commands = new Map<string, string[]>()
  const add = (name: string, label: string) => commands.set(name, [...(commands.get(name) ?? []), label])
  for (const [name, entry] of Object.entries(manifest.globalOptions)) add(name, `every command${where(entry)}`)
  for (const [path, row] of Object.entries(manifest.commands))
    for (const [name, entry] of Object.entries(row.options ?? {})) add(name, `\`${path}\`${where(entry)}`)

  const rows = Object.entries(manifest.options).map(([name, option]) => {
    const meaning = option.note ? `${option.meaning}. **${option.note}**` : option.meaning
    return `| \`${name}\` | ${option.value ? `\`${cell(option.value)}\`` : ""} | ${cell(meaning)} | ${
      option.default === undefined ? "" : `\`${cell(option.default)}\``
    } | ${(commands.get(name) ?? []).join(", ")} |`
  })
  return [
    CATALOGUE_START,
    "",
    "| Option | Value | Meaning | Default | Commands |",
    "|---|---|---|---|---|",
    ...rows,
    "",
    CATALOGUE_END,
  ].join("\n")
}

/** `page` with its catalogue replaced by `catalogue`; the markers must be there already. */
export const withCatalogue = (page: string, catalogue: string): string => {
  const start = page.indexOf(CATALOGUE_START)
  const end = page.indexOf(CATALOGUE_END)
  if (start === -1 || end === -1) throw new Error("the page has no option catalogue markers")
  return page.slice(0, start) + catalogue + page.slice(end + CATALOGUE_END.length)
}
