#!/usr/bin/env bash
# Usage: run.sh [sizes for the cost part, default "100000 1000000"]. Rewrites results.md below the marker;
# the human summary above it is kept as it is.
set -euo pipefail
cd "$(dirname "$0")"
SIZES="${1:-100000 1000000}"
SCRATCH="${STEMBENCH_SCRATCH:-/dev/shm/stemming-bench}"
# Kept between runs, so a rerun skips generating it; the databases stay in RAM so timings compare.
CORPUS="${STEMBENCH_CORPUS:-data/corpus}"
MARKER="<!-- generated by run.sh below this line -->"
R=results.md

[ -d node_modules ] || pnpm install --frozen-lockfile --ignore-workspace
[ -f ../../dist/store/sqlite/stems.js ] || (cd ../.. && pnpm build)
./download.sh
[ -f "$R" ] && grep -q "$MARKER" "$R" && sed -i "/$MARKER/q" "$R" || echo "$MARKER" > "$R"
{
  echo
  echo "## Environment [run]"
  echo
  echo "- $(lscpu | sed -n 's/^Model name: *//p') ($(nproc) threads), $(free -g | awk '/Mem:/ {print $2}') GB RAM, $(uname -sr)."
  echo "- node $(node --version), SQLite $(node -e 'const {DatabaseSync}=require("node:sqlite");console.log(new DatabaseSync(":memory:").prepare("select sqlite_version() v").get().v)') (node:sqlite)."
  echo "- Stemmer: official Snowball 3.1.1 JavaScript, generated by download.sh from snowballstem/snowball cd195b5 (BSD-3-Clause)."
  echo "- Treebanks at UD r2.18 commits pinned in download.sh; only aggregates and a few short words are committed."
  echo
} >> "$R"
node stemmers.ts > /dev/null
for corpus in syntagrus ru-gsd ancora ewt; do node quality.ts "$corpus" > /dev/null; done

echo "## Cost — synthetic corpus (bench/search/gen.ts, seed 42) [run]" >> "$R"
echo >> "$R"
mkdir -p "$SCRATCH" "$CORPUS"
CORPUS="$(cd "$CORPUS" && pwd)"
for n in $SIZES; do
  [ -s "$CORPUS/corpus-$n.tsv" ] || (cd ../search && SEARCHBENCH_DATA="$CORPUS" node gen.ts "$n" > /dev/null)
  SEARCHBENCH_DATA="$CORPUS" STEMBENCH_DB="$SCRATCH" node cost.ts "$n" > /dev/null
done

echo "## Gate §S12 — through the store code (gate.ts) [run]" >> "$R"
echo >> "$R"
for n in $SIZES; do
  SEARCHBENCH_DATA="$CORPUS" STEMBENCH_DB="$SCRATCH" node gate.ts "$n" > /dev/null
done
